version: '3'
services:
  rprj-web:
    build: .
    environment:
      SITE_TITLE: Cippa Lippa
    ports:
    - "8080:80"
    depends_on:
      - rprj-db
  rprj-db:
    #image: mariadb:10.3
    build:
      dockerfile: Dockerfile_db
    environment:
      MYSQL_ROOT_PASSWORD: mysecret
      MYSQL_DATABASE: rproject
    ports:
    - "3306:3306"
    volumes:
    - ./testdb:/var/lib/mysql
    #- "$PRJ_HOME"/mariadb:/var/lib/mysql
    #- "${PRJ_HOME}/mariadb:/var/lib/mysql"
    #- ./testdb:/var/lib/mysql
