version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile_app
      tags:
      - "rprj-app:${RPRJ_TAG}"
    ports:
    - "8081:3000"
    depends_on:
    - web
  web:
    build:
      context: .
      dockerfile: Dockerfile_web
      tags:
      - "rprj-web:${RPRJ_TAG}"
    environment:
      SITE_TITLE: ":: R-Project ::"
      SITE_TITLE_2: "A CMS Project"
      RPRJ_ADMIN_PASS: mysecretpass
      RPRJ_ROOT_OBJ: -10
      RPRJ_DB_SCHEMA: rprj
      MYSQL_APP: db
      MYSQL_USER: root
    ports:
    - "8080:80"
    volumes:
    - ./files:/var/www/html/files
    - ./files:/var/www/html/mng/files
    depends_on:
      - db
  db:
    build:
      context: .
      dockerfile: Dockerfile_db
      tags:
      - "rprj-db:${RPRJ_TAG}"
    environment:
      MYSQL_ROOT_PASSWORD: mysecret
      MYSQL_DATABASE: rproject
    #ports:
    #- "3306:3306"
    volumes:
    - ./mariadb:/var/lib/mysql
