FROM node:18-alpine

# Apparently a package needs a recent python

#ENV PYTHONUNBUFFERED=1
RUN apk add --no-cache python3 py3-pip make g++
#RUN apk add --update --no-cache python3 && ln -sf python3 /usr/bin/python
#RUN python3 -m ensurepip
#RUN pip3 install --no-cache --upgrade pip setuptools



WORKDIR /usr/src/app

#COPY rprj-app/package*.json ./
COPY rprj-app/package.json ./
# Bundle app source
COPY rprj-app/ .
COPY rprj-app/docker-entrypoint.sh /usr/local/bin/docker-entrypoint.sh
RUN rm package-lock.json
RUN rm -rf node_modules

#RUN npm install -g npm@9.6.6
RUN npm install -g npm@10.2.0
#RUN npm --version

# See: https://mherman.org/blog/dockerizing-a-react-app/
RUN npm install
# --silent

RUN npm install react-scripts@5.0.0 -g

# If you are building your code for production
# RUN npm ci --only=production

# RUN npm rebuild node-sass

CMD [ "npm", "start" ]
