FROM php:7.4-apache
# FROM php:8.1-apache
# FROM php:7.0-apache
# Install mysqli
RUN docker-php-ext-install mysqli && docker-php-ext-enable mysqli

# See: https://stackoverflow.com/questions/39657058/installing-gd-in-docker
RUN apt-get update -y && apt-get install -y apt-utils \
    libwebp-dev libjpeg62-turbo-dev libpng-dev libxpm-dev \
    libfreetype6-dev
RUN apt-get update && \
    apt-get install -y \
        zlib1g-dev 

# # It doesn't work with php-8
# RUN docker-php-ext-install mbstring

RUN apt-get install -y libzip-dev
RUN docker-php-ext-install zip

# # It doesn't work with php-8
# RUN docker-php-ext-configure gd --with-gd --with-webp-dir --with-jpeg-dir \
#     --with-png-dir --with-zlib-dir --with-xpm-dir --with-freetype-dir \
#     --enable-gd-native-ttf

RUN docker-php-ext-install gd

# Copy the source
#COPY php/ /var/www/html/

