---
# ansible-playbook -i ./hosts rprj_all.yml rprj_db.yml rprj.yml

- hosts: R-Prj
  become: yes
  become_user: root
  vars_files:
    - config.yml
  #vars:
    #git_dir: /opt/rprj
    #www_dir: /var/www/rprj
    #db_host: localhost
    #db_name: rproject
    #db_user: rprj
    #db_password: mysecretpass
    #db_root_password: rprjrootpwd

  tasks:

  - name: Install Packages
    apt:
      name:
      - "{{ dbpkg }}"
      - php
      - php-mysql
      - python-selinux

  - name: Enable Apache Modules
    apache2_module:
      state: present
      name: ssl

  - name: Ensure apache2 is running
    service:
      name: apache2
      state: started

  - name: GIT clone and update
    git:
      repo: https://git.code.sf.net/p/r-prj/gitcode
      dest: "{{ git_dir }}"
      version: master
    register: git_updated
  #- debug: "msg={{ git_updated.changed }}"

  - name: Remove default site
    file:
      path: /etc/apache2/sites-enabled/000-default.conf
      state: absent

  - name: Copy apache config if git changed
    copy:
      src: templates/rprj.conf
      dest: /etc/apache2/sites-available/rprj.conf
    when: git_updated.changed

  - name: Copy apache SSL config if git changed
    copy:
      src: templates/ssl_rprj.conf
      dest: /etc/apache2/sites-available/ssl_rprj.conf
    when: git_updated.changed

  - name: Link default default site
    file:
      src: /etc/apache2/sites-available/rprj.conf
      dest: /etc/apache2/sites-enabled/rprj.conf
      state: link
    when: git_updated.changed
    notify: Restart Apache Service

  - name: Link default default SSL site
    file:
      src: /etc/apache2/sites-available/ssl_rprj.conf
      dest: /etc/apache2/sites-enabled/ssl_rprj.conf
      state: link
    when: git_updated.changed
    notify: Restart Apache Service

  - name: Create a directory if it does not exist
    file:
      path: "{{ www_dir }}"
      state: directory
      mode: '0755'

  - name: Copy the PHP sources
    command:
      cmd: "cp -R {{ git_dir }}/php/ {{ www_dir }}/"
    when: git_updated.changed

  #- name: Copy config_local.php
    #command:
      #cmd: "cp {{ git_dir }}/php/config_local.php {{ www_dir }}/php/"
    #when: git_updated.changed or db_updated.changed

  #- name: config_local.php - server name
    #command:
      #cmd: "sed -i 's/db_server = \".*\"/db_server = \"{{ db_host }}\"/g' {{ www_dir }}/php/config_local.php"
    #when: git_updated.changed or db_updated.changed

  #- name: config_local.php - mysql db name
    #command:
      #cmd: "sed -i 's/db_db = \".*\"/db_db = \"{{ db_name }}\"/g' {{ www_dir }}/php/config_local.php"
    #when: git_updated.changed or db_updated.changed

  #- name: config_local.php - mysql user name
    #command:
      #cmd: "sed -i 's/db_user = \".*\"/db_user = \"{{ db_user }}\"/g' {{ www_dir }}/php/config_local.php"
    #when: git_updated.changed or db_updated.changed

  #- name: config_local.php - mysql user password
    #command:
      #cmd: "sed -i 's/db_pwd = \".*\"/db_pwd = \"{{ db_password }}\"/g' {{ www_dir }}/php/config_local.php"
    #when: git_updated.changed or db_updated.changed

  #- name: config_local.php - mysql db_schema
    #command:
      #cmd: "sed -i 's/db_schema = \".*\"/db_schema = \"{{ db_schema }}\"/g' {{ www_dir }}/php/config_local.php"
    #when: git_updated.changed or db_updated.changed

  - name: config_local.php
    template:
      src: templates/config_local.php.j2
      dest: "{{ www_dir }}/php/config_local.php"
      mode: '0755'
      owner: www-data
      group: www-data
    #when: git_updated.changed or db_updated.changed

  - name: Create a directory if it does not exist
    file:
      path: "{{ www_dir }}/php/files"
      state: directory
      mode: '0755'
      owner: www-data
      group: www-data

  - name: Link files dir in mng folder
    file:
      src: "{{ www_dir }}/php/files"
      dest: "{{ www_dir }}/php/mng/files"
      state: link

  - name: Restart Apache Service if git changed
    service:
      name: apache2
      state: restarted
    when: git_updated.changed

  handlers:
  - name: Restart Apache Service
    service:
      name: apache2
      state: restarted
